### ISSUE TITLE
[FEATURE] Add age as possible filter variable

### ISSUE THREAD

**Issue by tinneuro** [United4Surveillance/signal-detection-tool#293]
**Is your feature request related to a problem? Please describe.**

It is a nice additional feature to allow the user to filter by the age variable directly when available. 

**Describe the Solution You'd Like**

Here the filter would need to be adapted so the user can put a range for the age values and in the background the dataset is filtered. Furthermore the age variable should only be allowed as filter but not as stratification.

**Describe Alternatives**

**Additional Context**

**Comment by aj-thl** [comment]
I started working on this and created a branch: [feature/add_age_as_filter_variable](https://github.com/United4Surveillance/signal-detection-tool/tree/feature/add_age_as_filter_variable). In the branch the age has already been added as a possible filter variable. 

However, at the moment age groups do not now work logically if one is using the age in the filtering. For example, if one filters for ages between 0 and 50, in the signals tab there are still age groups present in the results that are outside of the minimum and maximum value. I think that this is caused by the fact that the age groups are currently created before any pre-processing. Maybe I need to investigate whether it is easy to move the creation of age groups to the pre-processing of the data. 

Anyway, I did not want to make a pull request yet since I'm on holiday from 8.7. to 11.8. and it would just hang there for a long time. But I wrote this down here and will continue to work on it after my holiday.

**Comment by aj-thl** [comment]
Thanks! If it's not too much trouble you could dig up the code. Sounds like it could be useful. In any case, don't spend too much time on this and there's certainly no rush now since I'm away.

**Comment by tinneuro** [comment]
So this is in the mod_tabpanel_input.R script in line 299-302 where the age_group levels get updated. What you also see is that I created some environment within the app where I store the age group levels. I was not sure whether this is the best way to do it but it works. In this way I could update things because they are stored somewhere. In levels.R you can see that I call in line 99 the stored levels when using the function age_group_levels(). In the script app_config.R I create the environment.

**Comment by aj-thl** [comment]
Thanks @tinneuro! This was very helpful and I used similar approach to get the filtering of age working properly with the age groups. There is still one minor thing: if user select both age and age group as a filtering variable it is possible for the user to make conflicting choices. For example, one can filter age < 50 and age group 60-69. I don't know if we want to fix this in the code or leave it to the user to check if the filtering makes sense. 

I will make a pull request about this now and maybe we can continue discussion there.
